.github/workflows/build-and-deploy.yml
.github/workflows/build-only.yml
.gitignore

mise en place d'un workflow github pour verfiier le fonctionnement de la ci durant les merges requests

mise en place d'un workflow ci avant les merge

---

src/components/Global/Footer.js

feat(#20): 🐝 huge & important updates !

---

src/pages/search.js

fix(#85): 🐛 corriger(search.js) : changer la clé de l'élément de la liste de résultats pour correspondre à la nouvelle structure de données
🔨 refactor(search.js) : ajouter des points-virgules manquants et supprimer des espaces inutiles
✨ fonctionnalité(search.js) : afficher les informations de spécialité et de ville des résultats de recherche Le code a été formaté pour améliorer la lisibilité et la cohérence. Les noms de propriétés HTML ont été mis en minuscules pour respecter les conventions. La clé de l'élément de la liste de résultats a été changée pour correspondre à la nouvelle structure de données. Les informations de spécialité et de ville des résultats de recherche sont maintenant affichées pour aider l'utilisateur à trouver plus facilement les résultats pert

fix(#85): 🐛 corriger(search.js) : changer la clé de l'élément de la liste de résultats pour correspondre à la nouvelle structure de données

---

.imgbotconfig

La configuration ImgBot a été ajoutée pour optimiser les images dans le référentiel. La configuration spécifie que les fichiers .jpg, .png et .webp doivent être ignorés, que la compression agressive est désactivée et que la compression Wiki est activée. La configuration spécifie également que le titre de la pull request doit commencer par "chores(🤖ImgBot) : Optimize images" pour faciliter l'identification des pull requests générées par ImgBot.

🆕 ajout(.imgbotconfig) : ajouter la configuration ImgBot

---

src/components/Global/Nav.js

Le logo inutile a été supprimé pour améliorer les performances de l'application.

fix(#91): 🔥supprimer le logo inutile

---

src/pages/search.js

Le code a été réorganisé pour améliorer la lisibilité et la maintenabilité. Les variables ont été initialisées avec des points-virgules pour éviter les erreurs de syntaxe. La fonction performSearch a été modifiée pour stocker la dernière recherche effectuée et éviter les appels inutiles à l'API. Le code HTML a été modifié pour utiliser des guillemets simples plutôt que doubles pour améliorer la cohérence.
🎨 style(search.js) : formater le code pour améliorer la lisibilité Le code a été formaté pour améliorer la lisibilité et la cohérence. Les guillemets simples ont été remplacés par des guillemets doubles pour améliorer la cohérence avec les conventions de style JavaScript. Les espaces ont été ajoutés pour améliorer la lisibilité et la cohérence.

refactor(#90) : 🔨  réorganiser le code pour améliorer la lisibilité

---

src/pages/search.js

fix(#85): 🐛 corriger(search.js) : changer la clé de l'élément de la liste de résultats pour correspondre à la nouvelle structure de données

fix(#85): 🐛 ajouter les images aux resultats de la recherche

---

src/components/Global/Hero.js
src/components/Maquilleuse/Advantages.js
src/pages/index.js
src/pages/maquilleuse.js

feat(#26): ✨ add page "Pourquoi My Makeup ?" with advantages of joining the platform as a makeup artist.

feat(#26): ✨ add page "Pourquoi My Makeup ?" with advantages of joining the platform as a makeup artist.

---

src/pages/index.js

ajout d'un point d'exclamation

---

src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
src/pages/api/auth/[...nextauth].js
src/pages/api/sendMail.js
src/pages/auth/error.js
src/pages/auth/init-account.js
src/pages/auth/profil.js
src/pages/auth/signup.js
src/pages/auth/verification-complete.js
src/pages/auth/verification-wall.js
src/pages/blog/[id].js
src/services/PatchMeMakeup.js

feat(https://github.com/For-Hives/my-makeup/pull/65): ✨ créer une nouvelle page pour l'initialisation du compte utilisateur
reprise de la mr #65  pour finaliser l'inscription
Completion du ticket #42

feat(#65): ✨ créer une nouvelle page pour l'initialisation du compte utilisateur 

---

src/components/Maquilleuse/AdvantagesMaquillleuse.js
src/components/Particulier/AdvantagesParticulier.js
src/pages/maquilleuse.js
src/pages/particulier.js

✨ fonctionnalité(AdvantagesParticulier.js) : ajouter un composant pour afficher les avantages de My Makeup pour les particuliers
✨ fonctionnalité(maquilleuse.js) : renommer le composant Advantages en AdvantagesMaquilleuse
✨ fonctionnalité(particulier.js) : ajouter un composant pour afficher les avantages de My Makeup pour les particuliers

feat(#22) : page pourquoi my makeup, pour les particulier

---

src/pages/search.js

- #218 
🐛 corriger(search.js) : corriger l'indentation et la mise en forme du code
🎨 style(search.js) : ajouter une condition pour afficher le badge de super maquilleuse uniquement si result.pro est vrai

Feat(#218): Badge pro condition

---

src/components/Global/Info.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
src/components/Profil/Childs/Views/ViewPortfolioProfil.js
src/components/Profil/Parents/ResumeProfil.js
src/pages/api/auth/[...nextauth].js
src/pages/auth/error.js
src/pages/auth/signup.js
src/pages/search.js
src/pages/sitemap.xml.js

Feat(#243): Limitation du nombre d'upload & sitemap fix

---

src/components/Global/CTA.js
src/components/Global/Hero.js
src/components/Global/Search/SearchBloc.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
src/components/Profil/Parents/ResumeProfil.js
src/pages/auth/signup.js
src/pages/solutions/pour-les-maquilleuses.js
src/pages/solutions/pour-les-particuliers.js

- #261 
- #257 
~ fix les problèmes ciblés de la search console

Feat(#261): Mettre des valeurs maximales pour tous les champs, côté api & front

---

cypress/e2e/auth/profil-edge.cy.js
cypress/e2e/auth/profil-update-then-search.cy.js
src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js

- #312 
- #313 
- #314 
- #315 
- #316 
- #317 
- #318 
- #319

Feat(#312): Search & fix tests

---

src/pages/auth/init-account.js

Eviter trop de call useless vers l'api, on repassera au fonctionnement que tu avais prévu plus tard ;p

Feat(#386): Bug/Feat, refactor init account

---

.github/workflows/build-test.yml
.github/workflows/deploy-preprod.yml
.github/workflows/deploy-prod.yml

#420 
🔧 corriger(build-test.yml) : mettre à jour les variables d'environnement NEXT_PUBLIC_URL
🔧 corriger(deploy-preprod.yml) : mettre à jour les variables d'environnement NEXT_PUBLIC_URL
🔧 corriger(deploy-prod.yml) : mettre à jour les variables d'environnement NEXT_PUBLIC_URL
Les variables d'environnement NEXT_PUBLIC_URL sont mises à jour pour correspondre à la valeur de la variable d'environnement NEXT_PUBLIC_URL spécifiée dans les secrets. Cela permet de configurer correctement l'URL publique de l'application lors de la construction et du déploiement sur les environnements de préproduction et de production.

Corriger les doubles / dans la sitemap

---

.github/workflows/build-test.yml
.gitignore
sonar-project.properties

🔧 corriger(build-test.yml) : supprimer les espaces supplémentaires da…ns les listes de conteneurs
🔧 corriger(build-test.yml) : ajouter des guillemets autour des valeurs de branches dans l'événement pull_request ✨ fonctionnalité(build-test.yml) : ajouter une étape pour l'analyse SonarQube ✨ fonctionnalité(sonar-project.properties) : ajouter le fichier de configuration SonarQube Les espaces supplémentaires dans les listes de conteneurs ont été supprimés pour améliorer la lisibilité du fichier. Des guillemets ont été ajoutés autour des valeurs de branches dans l'événement pull_request pour assurer la compatibilité avec la syntaxe YAML. Une nouvelle étape a été ajoutée pour exécuter l'analyse SonarQube, en utilisant

Setup SonnarQube

---

src/pages/blog/[id].js
src/pages/profil/[username].js
src/pages/talent/[slug].js

Feat(#425): fallback blocking

---

app/page.js
src/components/Global/Nav.js
src/components/Global/Search/SearchBloc.js

Must be threated after PR: #693

V2 694 migrate index page to app router
